<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework><LangVersion>latest</LangVersion><NoWarn>0649;0169</NoWarn><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../mod/MapPositionProtocol.cs" Link="MapPositionProtocol.cs" />
    <Compile Include="../../mod/MapSharingIntegration.cs" Link="MapSharingIntegration.cs" />
    <Compile Include="../../mod/NetworkFeaturePatch.cs" Link="NetworkFeaturePatch.cs" />
    <Compile Include="../../mod/NetworkEnhancementContracts.cs" Link="NetworkEnhancementContracts.cs" />
    <Compile Include="../../mod/AdvancedReplication.cs" Link="AdvancedReplication.cs" />
    <Compile Include="../../mod/ZdoCompression.cs" Link="ZdoCompression.cs" />
    <Compile Include="../../mod/CompressionSession.cs" Link="CompressionSession.cs" />
    <Compile Include="../../mod/LosslessZdoCodec.cs" Link="LosslessZdoCodec.cs" />
    <Compile Include="../../mod/SteamRateLease.cs" Link="SteamRateLease.cs" />
    <Compile Include="../../mod/SendZdoTransform.cs" Link="SendZdoTransform.cs" />

    <Compile Include="../../mod/ServerImprovementMetrics.cs" Link="ServerImprovementMetrics.cs" />
    <Compile Include="../../mod/SendWindowPolicy.cs" Link="SendWindowPolicy.cs" />
<Compile Include="../../mod/ClientTelemetryModel.cs" Link="ClientTelemetryModel.cs" />
<Compile Include="../../mod/ReplicationIntegration.cs" Link="ReplicationIntegration.cs" />
<Compile Include="../../mod/FairScheduler.cs" Link="FairScheduler.cs" />
<Compile Include="../../mod/TelemetryModel.cs" Link="TelemetryModel.cs" />
<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
<Compile Include="../../mod/IntegrationState.cs" Link="IntegrationState.cs" />
<Compile Include="../../mod/TelemetryIntegration.cs" Link="TelemetryIntegration.cs" />
</ItemGroup>
<Import Project="../HarmonyRuntime.props" />
</Project>
